post_install() {
	echo "------------------------------------------------------------"
	echo ">Place your favourite OpenBSD iso image(s) in /opt/openbsd/<"
	echo "> To have them added to grub automatically, run            <"
	echo ">   grub-mkconfig -o /boot/grub/grub.cfg                   <"
	echo "------------------------------------------------------------"
}

post_upgrade() {
	post_install
}

post_remove() {
	echo "------------------------------------------------------------"
	echo ">You may want to erase your OpenBSD images in /opt/openbsd/<"
	echo "> and regenerate your grub config by running               <"
	echo ">   grub-mkconfig -o /boot/grub/grub.cfg                   <"
	echo "------------------------------------------------------------"
}
